services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: agrinode-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ../mosquitto/config:/mosquitto/config
      - ../mosquitto/data:/mosquitto/data
      - ../mosquitto/log:/mosquitto/log
    restart: unless-stopped

  postgres-db:
    image: postgres:15
    container_name: agrinode-postgres
    environment:
      POSTGRES_USER: agrinode_admin
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: agrinode
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: agrinode-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@agrinode.local
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - postgres-db
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: agrinode-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    restart: unless-stopped

  agrinode-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: always
    # We do NOT map ports to the host. We want this hidden behind Nginx!
    depends_on:
      - postgres-db
    deploy:
      replicas: 2 # THIS IS THE BOSS MOVE: Spin up TWO identical Go APIs

  nginx:
    image: nginx:latest
    ports:
      - "80:80" # This is the ONLY open door to the outside world
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - agrinode-api

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: agrinode-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: unless-stopped

volumes:
  postgres-data: